### ISSUE TITLE
please tag and release on GitHub

### ISSUE THREAD

**Issue by GitMensch** [DrMerfy/vscode-overtype#1]
Thank you very much for this fork and the re-release.

Can you please tag your 0.3.0/0.3.1 and via GitHub make those a release (+ at least for the newest version attach the vsix to it), too? And ideally also updating ChangeLog.md?

Again: thank you very much for bringing life back to this extension.

**Comment by DrMerfy** [comment]
Hey @GitMensch,
it was thanks to you :D 

Yes, it can be done! 

You look like having some experience with projects like that. Do you write yourself? Would you like to be a collaborator on this repository?

**Comment by GitMensch** [comment]
> You look like having some experience with projects like that. 

A bit. My possibly biggest "effect" on GitHub is likely the work on https://github.com/Bill-Gray/PDCursesMod.

> Do you write yourself?

Yes, but not in Typescript so far (I'm a C and COBOL guy), but I _think_ I may find enough time in the next weeks to check #2 - if you can provide me with a hint how to register to the caps-lock event then feel free to assign it to me.

**Comment by GitMensch** [comment]
... and I'd opt to handle this issue, too (but that obviously needs more access rights for tagging and for release management).

**Comment by DrMerfy** [comment]
Nicely done! That is a huge project, I see that you are in close contact with lexical analysis and abstract trees generation, that is awesome.

Have taken a look in the past, but the road did lead me in a completely different way. I admire those who build the building blocks of our times.

Anyway, you should be a collaborator now :D (An invite should have come somewhere)

Just added the release. Feel free to take #2 ! I'll take a look my self about that event handler and update it there. Cheers!
