### ISSUE TITLE
What is "readme badges" about?

### ISSUE THREAD

**Issue by GitMensch** [DrMerfy/vscode-overtype#12]
If we don't see use in that I suggest to drop it from the README and move the "all contributors" there (and add @AdamMaras and @DrMerfy to it).

**Comment by DrMerfy** [comment]
Mhm I'll remove it know, good idea.

**Comment by GitMensch** [comment]
Hm, if I understand the bot and the [Emoji Key](https://allcontributors.org/docs/en/emoji-key) correct, may I request an additional code contrib for #11? I'm keen to check if "links to code contributions of this project" is an actual working link...

**Comment by DrMerfy** [comment]
Ofc, I'll add it there :D

**Comment by GitMensch** [comment]
... and the generated link works :-)
Hm... I still thank that, if we want to keep the contributors badge then we should move it to the "badge line" (as last entry) - but as the counter "1" looks quite ugly possibly just drop the counter (for now) or may add the original author and you to the contributors?
