### ISSUE TITLE
Idea: remove "Visual Studio Code" from the README's title

### ISSUE THREAD

**Issue by GitMensch** [DrMerfy/vscode-overtype#15]
Reasoning: it works on every vscode based editors (I personally only use VSCodium, for example) but "vscode based editors" seems like a bad choice for a title, maybe replace it by something else and reference "vscode based editors" somewhere in the text, possibly with inline links to VSCodium and Visual Studio Code (not sure yet if these should target the repos or the "product websites").

I'm very likely biased here, so assigning to @DrMerfy (close with a short response would be ok, too)

**Comment by DrMerfy** [comment]
If you are using VSCodium (I use VSCode) then it is a good idea to drop the VSCode from the title, as we can test it in it too. I'll make the change.

**Comment by GitMensch** [comment]
We both use "vscode" :-) I guess you use the binaries shipped and "enhanced" by Microsoft which they gave the product name "Visual Studio Code" and I use the VSCodium binaries (so vscode but no telemetry and no proprietary extensions). If it does not come down to use some of Microsofts proprietary extensions then it is the same experience as it uses vscode (which itself heavily uses electron) and inbuilt-extensions.

But because of your message I've just checked: this extension works fine in Eclipse Theia (tested with the webbrowser instance from Gitpod), too, everything that works there works in the Dekstop version, too. If you haven't tried that yet I highly suggest to do so, for example via Gitpod.

So yes: its quite universal and seems to work in all editors that support vscode based vsix. I'll leave it to you to find the correct words for the README :-)

**Comment by DrMerfy** [comment]
Also, as we are here afterall. @all-contributors please add @AdamMaras to the contributors for code

**Comment by DrMerfy** [comment]
And please, add @DrMerfy to the contributors for projectManagement

**Comment by DrMerfy** [comment]
And please @all-contributors, add @DrMerfy to the contributors for projectManagement

**Comment by DrMerfy** [comment]
I guess I cannot add myself :D
