### ISSUE TITLE
Characters are sometimes inserted instead of overtyped

### ISSUE THREAD

**Issue by pewscorner** [DrMerfy/vscode-overtype#23]
**Steps to reproduce**
Open a fresh editor and enter 2 identical lines of text, e.g.:
```
012345678901234567890123456789012345678901234567890123456789
012345678901234567890123456789012345678901234567890123456789
```
Now switch to overtype mode, place the cursor at the start of the second line, and start typing rapidly. The following shows the result of one such test where the problem occurred after typing only 4 characters ("asdf"):
```
012345678901234567890123456789012345678901234567890123456789
asdf345678901234567890123456789012345678901234567890123456789
```
As shown, the 4 new characters replaced only 3 old ones, so the line length was increased by 1. This ought not to happen in overtype mode.

**Versions**
VS Code 1.60.2 on Windows 10
Overtype v0.4.0

Tested with all other extensions disabled.

**Comment by DominoPivot** [comment]
To clarify, if multiple characters are typed in a very short timespan, all typed characters are inserted behind the caret but only one character is removed after the caret.

**Comment by pewscorner** [comment]
I can't reproduce this anymore with Overtype v0.4.0 (or the newer Overtype v0.4.7). VS Code version is now 1.73.1.

**Comment by GitMensch** [comment]
Can anyone still reproduce that with recent vscode and overtype or should this be closed?

**Comment by pewscorner** [comment]
I still can't reproduce it with Overtype v0.5.0 and VS Code 1.77.0 - and I've tried really hard.
