### ISSUE TITLE
Improvement: Set the correct activation events

### ISSUE THREAD

**Issue by DrMerfy** [DrMerfy/vscode-overtype#30]
Currently we are using * as the activation event, this causes the extension to [be slower.](https://code.visualstudio.com/api/references/activation-events#Start-up)

We should set some more specific activation events.

**Comment by GitMensch** [comment]
This _may_ relate to #33 - @DrMerfy Did you checked which activation events would be correct?

**Comment by DrMerfy** [comment]
Hey @GitMensch probably the best option is to use the onStartupFinished event, it should improve loading performance by some. Another idea would be to let it enable when the toggle command is trigered but that would mean that the user will not have access to the typing mode indicator before triggering the command.

![image](https://user-images.githubusercontent.com/21154979/229285435-87feae72-3817-40fa-ab1a-0e09d7570d32.png)

Pushed the changes (and a slightly adjusted icon to reflect the project in general) in master. Could you please take a look that it works in your environment as well with the adjusted activation events?

**Comment by GitMensch** [comment]
> probably the best option is to use the onStartupFinished event

agreed.

LGTM, also for use with remote workspaces; so time to update ChangeLog and release, I think :-)
