### ISSUE TITLE
[Request] A setting to override the behaviour of backspace

### ISSUE THREAD

**Issue by MaddyGuthridge** [DrMerfy/vscode-overtype#32]
It'd be cool if the extension could make backspace behave like a left arrow key (and similar for delete).

**Comment by jkyeung** [comment]
This seems like a subset or variant of the ideas discussed in #20. As such, I think this issue should probably be merged with that one.

That said, I think this is the "most correct" behavior for the backspace key in overtype mode, and the current title is actually more general and less confusing (to me) than #20.

I am a little confused by "and similar for delete" though. Is the proposal to make the delete key behave *exactly the same* as backspace? Or to make both backspace and delete independently configurable?

Personally, my wish list would be for backspace to be identical to left arrow while in overtype mode, and for delete to keep its existing behavior regardless of mode. (Or, if we're going to make delete configurable, then I would possibly include the option to make the delete key mean "delete the rest of the line" while in overtype mode.)

**Comment by MaddyGuthridge** [comment]
Yep, I was considering having backspace be left arrow and delete be right arrow. Backspace for undo from #20 might be even more logical though. Either way I think it's pretty clear that different people have different desires for what the behaviour would be so having independent configuration would by far be the best option.
