### ISSUE TITLE
FR: add setting to disable the insert lable/toggle

### ISSUE THREAD

**Issue by GitMensch** [DrMerfy/vscode-overtype#4]
Taken from https://github.com/AdamMaras/vscode-overtype/issues/3

> The cursor appearance change is enough indication, so an option to hide the status altogether (instead of just abbreviating) might save space in the status bar.

with an answer of @AdamMaras

> Hey, that is a spectacular idea!

I also see how that would be useful for some people.

**Comment by djoffe** [comment]
Hi @GitMensch, @DrMerfy,

Thanks for picking up the work on this extension!

**Comment by GitMensch** [comment]
Maybe this setting should be dropped in favor of #9 and allow setting the text for both insert and overtype to nothing? This way we would have two settings (the two label texts) instead of two settings (the boolean abbreviated and show/hide).
