### ISSUE TITLE
Idea: replace abbreviatedStatus setting with freely adjustable text (possibly including none)

### ISSUE THREAD

**Issue by GitMensch** [DrMerfy/vscode-overtype#9]
I've played around with this a bit and think it would be "clean" to replace the one boolean setting `abbreviatedStatus` by two string settings `textInsertMode` (default: "Insert") and `textOvertypeMode` (default: "Overtype").

Con for the change: likely will lead to some inconvenience for some users which will "need" to adjust the new setting and get a warning message in their settings that the old one is unknown

Pro for the change: allows people to localize (or abbreviate) as they want and to have the same result as with other editors / IDEs (for example Visual Studio shows "OVR" if active and nothing otherwise - which I'd internally set if both trimmed versions are identical [normally: empty]).

@DrMerfy Are you OK with me to do that change in master? I have 98% of the code already, only cleanup and ChangeLog is missing....

**Comment by DrMerfy** [comment]
Sounds good to me! You are putting a lot of effort on this project, @all-contributors please add @GitMensch to the contributors :)
